### ISSUE TITLE
MobileGestalt.h lacks any constants potentially introduced with iOS 9

### ISSUE THREAD

**Issue by ahyattdev** [Cykey/ios-reversed-headers#15]
https://github.com/Cykey/ios-reversed-headers/blob/master/MobileGestalt/MobileGestalt.h

Is there any chance that you could update this with whatever has changed?

Thanks @Cykey!

**Comment by Cykey** [comment]
[This](http://newosxbook.com/articles/guesstalt.html?n) website might have the newer keys.
